// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command generate_report aggregates test execution results, image metadata,
// and platform integrity measurements to generate a standardized QualificationReport textproto.
package main

//go:generate ../../proto/generate.sh

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/encoding/prototext"

	opb "github.com/openconfig/ondatra/proto"
	pcrpb "github.com/openconfig/qualification-reporter/proto"
	qrpb "github.com/openconfig/qualification-reporter/proto"
	ripb "github.com/openconfig/qualification-reporter/proto"
)

var (
	intentPath      = flag.String("intent", "", "Path to ReleaseIntent textproto file (required).")
	testResultsPath = flag.String("test_results", "", "Path to JSON-Lines test results file (.jsonl) generated by Ondatra (required).")
	imageMetaPath   = flag.String("image_metadata", "", "Path to ImageMetadata textproto file (required).")
	pcrResponsePath = flag.String("pcr_response", "", "Path to PCRResponse textproto file.")
	vendorName      = flag.String("vendor", "", "Vendor name: ARISTA, CISCO, JUNIPER, NOKIA (required).")
	commitIDFlag    = flag.String("featureprofiles_commit", "", "Git commit SHA of the openconfig/featureprofiles repository used during test execution (required).")
	outputPath      = flag.String("out", "qualification_report.textproto", "Output path for the generated QualificationReport textproto.")
)

var validVendors = map[string]qrpb.Vendor{
	"ARISTA":  qrpb.Vendor_VENDOR_ARISTA,
	"CISCO":   qrpb.Vendor_VENDOR_CISCO,
	"JUNIPER": qrpb.Vendor_VENDOR_JUNIPER,
	"NOKIA":   qrpb.Vendor_VENDOR_NOKIA,
}

var (
	gitSHARegex = regexp.MustCompile("^[0-9a-fA-F]{7,40}$")
	sha256Regex = regexp.MustCompile("^[0-9a-fA-F]{64}$")
	md5Regex    = regexp.MustCompile("^[0-9a-fA-F]{32}$")
)

const (
	// maxScanTokenSize is the maximum buffer size (10 MB) for scanning a single JSON-Lines
	// record, accommodating large test failure diagnostics, stack traces, or packet logs.
	maxScanTokenSize = 10 * 1024 * 1024
)

// validateFile verifies that the given path exists, is a regular file, and matches the expected extension if specified.
func validateFile(flagName, path, expectedExt string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("cannot access -%s file %q: %w", flagName, path, err)
	}
	if info.IsDir() {
		return fmt.Errorf("-%s path %q is a directory, expected a regular file", flagName, path)
	}
	if expectedExt != "" && !strings.HasSuffix(strings.ToLower(path), expectedExt) {
		return fmt.Errorf("-%s file %q has invalid extension; expected %s", flagName, path, expectedExt)
	}
	return nil
}

func validateFlags() error {
	var missing []string
	if *intentPath == "" {
		missing = append(missing, "-intent")
	}
	if *testResultsPath == "" {
		missing = append(missing, "-test_results")
	}
	if *imageMetaPath == "" {
		missing = append(missing, "-image_metadata")
	}
	if *vendorName == "" {
		missing = append(missing, "-vendor")
	}
	if *commitIDFlag == "" {
		missing = append(missing, "-featureprofiles_commit")
	}
	if *outputPath == "" {
		missing = append(missing, "-out")
	}

	if len(missing) > 0 {
		return fmt.Errorf("missing required flag(s): %s", strings.Join(missing, ", "))
	}

	if err := validateFile("intent", *intentPath, ".textproto"); err != nil {
		return err
	}
	if err := validateFile("test_results", *testResultsPath, ".jsonl"); err != nil {
		return err
	}
	if err := validateFile("image_metadata", *imageMetaPath, ".textproto"); err != nil {
		return err
	}
	if _, ok := validVendors[strings.ToUpper(*vendorName)]; !ok {
		return fmt.Errorf("invalid -vendor %q; must be one of ARISTA, CISCO, JUNIPER, NOKIA", *vendorName)
	}
	if !gitSHARegex.MatchString(*commitIDFlag) {
		return fmt.Errorf("invalid -featureprofiles_commit %q; expected a valid 7 to 40 character hexadecimal Git SHA", *commitIDFlag)
	}
	if !strings.HasSuffix(strings.ToLower(*outputPath), ".textproto") {
		return fmt.Errorf("-out file %q has invalid extension; expected .textproto", *outputPath)
	}
	if *pcrResponsePath != "" {
		if err := validateFile("pcr_response", *pcrResponsePath, ".textproto"); err != nil {
			return err
		}
	}
	return nil
}

func main() {
	flag.Parse()

	if err := validateFlags(); err != nil {
		log.Fatalf("Validation error: %v", err)
	}

	intentData, err := os.ReadFile(*intentPath)
	if err != nil {
		log.Fatalf("Failed to read release intent file %q: %v", *intentPath, err)
	}
	intent := &ripb.ReleaseIntent{}
	if err := prototext.Unmarshal(intentData, intent); err != nil {
		log.Fatalf("Failed to parse ReleaseIntent textproto from %q: %v", *intentPath, err)
	}
	if intent.GetReleaseId() == "" {
		log.Fatalf("Validation error in ReleaseIntent %q: release_id cannot be empty", *intentPath)
	}
	if len(intent.GetIntendedTestIds()) == 0 {
		log.Fatalf("Validation error in ReleaseIntent %q: intended_test_ids cannot be empty", *intentPath)
	}

	testMap, err := parseJSONLLedger(*testResultsPath)
	if err != nil {
		log.Fatalf("Failed to parse test results ledger %q: %v", *testResultsPath, err)
	}

	imgMeta, err := parseImageMetadata(*imageMetaPath)
	if err != nil {
		log.Fatalf("Failed to parse ImageMetadata: %v", err)
	}

	var pcrResp *pcrpb.PCRResponse
	if *pcrResponsePath != "" {
		pcrData, err := os.ReadFile(*pcrResponsePath)
		if err != nil {
			log.Fatalf("Failed to read -pcr_response file %q: %v", *pcrResponsePath, err)
		}
		pcrResp = &pcrpb.PCRResponse{}
		if err := prototext.Unmarshal(pcrData, pcrResp); err != nil {
			log.Fatalf("Failed to parse PCRResponse textproto from %q: %v", *pcrResponsePath, err)
		}
	}

	report, err := buildReport(intent, testMap, imgMeta, pcrResp, *vendorName, *commitIDFlag)
	if err != nil {
		log.Fatalf("Failed to build QualificationReport: %v", err)
	}

	if err := writeReport(report, *outputPath); err != nil {
		log.Fatalf("Failed to write QualificationReport: %v", err)
	}

	fmt.Printf("Successfully generated QualificationReport at: %s\n", *outputPath)
}

// parseImageMetadata reads, parses, and validates ImageMetadata textproto specifications.
func parseImageMetadata(metaPath string) (*qrpb.ImageMetadata, error) {
	imgMeta := &qrpb.ImageMetadata{}
	data, err := os.ReadFile(metaPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read image metadata file %q: %w", metaPath, err)
	}
	if err := prototext.Unmarshal(data, imgMeta); err != nil {
		return nil, fmt.Errorf("failed to parse ImageMetadata textproto from %q: %w", metaPath, err)
	}
	if imgMeta.GetImageName() == "" {
		return nil, fmt.Errorf("validation error in ImageMetadata %q: image_name cannot be empty", metaPath)
	}
	if imgMeta.GetSoftwareVersion() == "" {
		return nil, fmt.Errorf("validation error in ImageMetadata %q: software_version cannot be empty", metaPath)
	}

	switch c := imgMeta.GetChecksum().(type) {
	case *qrpb.ImageMetadata_Sha256:
		if !sha256Regex.MatchString(c.Sha256) {
			return nil, fmt.Errorf("validation error in ImageMetadata %q: invalid sha256 %q (expected 64 hex characters)", metaPath, c.Sha256)
		}
	case *qrpb.ImageMetadata_Md5:
		if !md5Regex.MatchString(c.Md5) {
			return nil, fmt.Errorf("validation error in ImageMetadata %q: invalid md5 %q (expected 32 hex characters)", metaPath, c.Md5)
		}
	default:
		return nil, fmt.Errorf("validation error in ImageMetadata %q: checksum (sha256 or md5) is required", metaPath)
	}

	return imgMeta, nil
}

// buildReport compiles the final QualificationReport protobuf message in deterministic order.
func buildReport(intent *ripb.ReleaseIntent, testMap map[string]*opb.TestResult, imgMeta *qrpb.ImageMetadata, pcrResp *pcrpb.PCRResponse, vendorStr, commitSHA string) (*qrpb.QualificationReport, error) {
	report := &qrpb.QualificationReport{
		ReleaseIntentId:         intent.GetReleaseId(),
		Vendor:                  validVendors[strings.ToUpper(vendorStr)],
		ImageMetadata:           imgMeta,
		PcrResponse:             pcrResp,
		FeatureprofilesCommitId: commitSHA,
	}

	intendedSet := make(map[string]bool, len(intent.GetIntendedTestIds()))
	for _, testID := range intent.GetIntendedTestIds() {
		intendedSet[testID] = true
		if tr, ok := testMap[testID]; ok {
			report.FeatureProfileTestResults = append(report.FeatureProfileTestResults, tr)
		} else {
			report.FeatureProfileTestResults = append(report.FeatureProfileTestResults, &opb.TestResult{
				TestId: testID,
				Status: opb.TestStatus_TEST_STATUS_NOT_RUN,
			})
		}
	}

	for testID := range testMap {
		if !intendedSet[testID] {
			log.Printf("Warning: test result for %q found in ledger is not listed in ReleaseIntent %q and will be omitted from the report", testID, intent.GetReleaseId())
		}
	}

	return report, nil
}

// writeReport serializes and writes the QualificationReport as a formatted textproto file.
//
// Rationale for overwriting existing output files:
// Report generation is an idempotent operation derived from the persistent Ondatra JSON-Lines ledger
// and input metadata specifications. Overwriting an existing output report rather than erroring or
// prompting for interactive confirmation ensures seamless integration with automated CI/CD
// pipelines where test executions or report generation steps may be retried.
func writeReport(report *qrpb.QualificationReport, outputPath string) error {
	outData, err := prototext.MarshalOptions{Multiline: true}.Marshal(report)
	if err != nil {
		return fmt.Errorf("failed to marshal QualificationReport textproto: %w", err)
	}

	if dir := filepath.Dir(outputPath); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory for report %q: %w", outputPath, err)
		}
	}

	header := "# proto-file: proto/qualification_report.proto\n# proto-message: openconfig.qualificationreporter.QualificationReport\n\n"
	if err := os.WriteFile(outputPath, append([]byte(header), outData...), 0644); err != nil {
		return fmt.Errorf("failed to write report to %q: %w", outputPath, err)
	}
	return nil
}

// isOlderExecution returns true if tr occurred before existing based on timestamps.
func isOlderExecution(tr, existing *opb.TestResult) bool {
	if tr.GetExecutionTimestamp() == nil || existing.GetExecutionTimestamp() == nil {
		return false
	}
	return tr.GetExecutionTimestamp().AsTime().Before(existing.GetExecutionTimestamp().AsTime())
}

// updateTestMapWithPriority updates testMap so that newer executions (by timestamp)
// supersede older ones. If timestamps are identical or missing, the latest record wins.
func updateTestMapWithPriority(testMap map[string]*opb.TestResult, tr *opb.TestResult) {
	existing, ok := testMap[tr.GetTestId()]
	if ok && isOlderExecution(tr, existing) {
		return
	}
	testMap[tr.GetTestId()] = tr
}

// parseJSONLLedger parses a JSON-Lines execution ledger file containing serialized TestResult objects and returns testMap.
func parseJSONLLedger(path string) (map[string]*opb.TestResult, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("unable to open ledger file %q: %w", path, err)
	}
	defer f.Close()

	testMap := make(map[string]*opb.TestResult)
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 64*1024), maxScanTokenSize)

	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		tr := &opb.TestResult{}
		if err := protojson.Unmarshal([]byte(line), tr); err != nil {
			return nil, fmt.Errorf("malformed JSON-Lines TestResult on line %d of %q: %w", lineNum, path, err)
		}

		if tr.GetTestId() == "" {
			continue
		}

		updateTestMapWithPriority(testMap, tr)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading ledger file %q: %w", path, err)
	}
	return testMap, nil
}
